### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by albingcj** [albingcj/bootstrap-practice#3]
needs more documentation

**Comment by sabhari-krr** [comment]
# Using Bootstrap 5

Bootstrap 5 is a popular front-end framework that simplifies web development by providing a collection of responsive CSS and JavaScript components. This README provides a quick guide on how to get started with Bootstrap 5 in your projects.

## Getting Started

1. **Installation:** Include Bootstrap 5 in your project using one of the following methods:
   - **CDN:** Add the Bootstrap CSS and JavaScript CDN links to your HTML file.
   - **npm:** Install Bootstrap using npm by running: `npm install bootstrap`

2. **HTML Structure:** Structure your HTML code using Bootstrap's predefined components, such as containers, rows, and columns.

## Basic Usage

### CSS Classes

Bootstrap provides a range of CSS classes that you can use to style your elements. Some common classes include:
- `.container` for creating a responsive container.
- `.row` for creating rows within a container.
- `.col` for creating columns within a row.

### Components

Bootstrap offers various components, like navigation bars, cards, forms, and buttons. These components can be customized by adding classes and attributes.

```html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Website</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
```

### JavaScript Components

Bootstrap 5 comes with several JavaScript components like modals, carousels, and dropdowns. To use these components, make sure you've included Bootstrap's JavaScript and follow their documentation.

## Customization

Bootstrap can be customized using Sass variables or by overriding default CSS styles. Refer to the Bootstrap documentation for details on customization options.

## Resources

- [Bootstrap Documentation](https://getbootstrap.com/docs/5.0/getting-started/introduction/)
- [Bootstrap Starter Templates](https://getbootstrap.com/docs/5.0/examples/)

## Conclusion

Bootstrap 5 streamlines front-end development by offering a wide range of responsive components and styles. Whether you're building a simple website or a complex web application, Bootstrap can save you time and effort while ensuring a consistent and appealing design.
